### ISSUE TITLE
Using Libman with IIS - File permissions issues

### ISSUE THREAD

**Issue by princeo** [aspnet/LibraryManager#373]
The files saved to disk by Libman has permission issues and prevents rendering when using the files with Bundles.

1. I have Libman managing Bootstrap and Jquery. 
2. I use Bundles to render the css and Javascripts to the pages using line @Styles.Render("~/Content/css")

### Expected result
Page should render with no errors.

### Actual result
When I run my project with IISExpress, That works fine. 
However when I map the project to a IIS website, I get an error when the page is rendering

### Further technical details
When I looked at the file permissions, there were just 3 users 
SYSTEM, [MySelf], Administrators so this is the issue. Also in explorer, the files have a padlock icon assigned to them.
 
As Visual studio generates files all the time, I expect this not to be an issue.
Stack trace below

``` Access to the path 'C:\Dev\XXXX\XXXX\XXXX\XXXX\lib\twitter-bootstrap\css\bootstrap.css' is denied.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.UnauthorizedAccessException: Access to the path 'C:\Dev\XXXX\XXXX\XXXX\XXXX\lib\twitter-bootstrap\css\bootstrap.css' is denied. 

ASP.NET is not authorized to access the requested resource. Consider granting access rights to the resource to the ASP.NET request identity. ASP.NET has a base process identity (typically {MACHINE}\ASPNET on IIS 5 or Network Service on IIS 6 and IIS 7, and the configured application pool identity on IIS 7.5) that is used if the application is not impersonating. If the application is impersonating via <identity impersonate="true"/>, the identity will be the anonymous user (typically IUSR_MACHINENAME) or the authenticated request user. 

To grant ASP.NET access to a file, right-click the file in File Explorer, choose "Properties" and select the Security tab. Click "Add" to add the appropriate user or group. Highlight the ASP.NET account, and check the boxes for the desired access.

Source Error:
Line 16:     @Styles.Render("~/Content/css")

```
```csharp
StackTrace

[UnauthorizedAccessException: Access to the path 'C:\XXXX\XXXX\XXXX\XXXX\XXXX\lib\twitter-bootstrap\css\bootstrap.css' is denied.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +417
   System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +1291
   System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) +123
   System.Web.Hosting.MapPathBasedVirtualFile.Open() +104
   System.Web.Optimization.BundleFile.ApplyTransforms() +61
   System.Web.Optimization.DefaultBundleBuilder.BuildBundleContent(Bundle bundle, BundleContext context, IEnumerable`1 files) +660
   System.Web.Optimization.Bundle.GenerateBundleResponse(BundleContext context) +188
   System.Web.Optimization.Bundle.GetBundleResponse(BundleContext context) +59
   System.Web.Optimization.BundleResolver.GetBundleContents(String virtualPath) +213
   System.Web.Optimization.AssetManager.DeterminePathsToRender(IEnumerable`1 assets) +406
   System.Web.Optimization.AssetManager.RenderExplicit(String tagFormat, String[] paths) +34
   ASP._Page_Views_Master_cshtml.Execute() in c:\Dev\XXXX\XXXX\XXXX\XXXX\Views\Master.cshtml:16
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +252
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +122
   System.Web.WebPages.<>c__DisplayClass40_0.<RenderPageCore>b__0(TextWriter writer) +309
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +108
   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +89
   System.Web.WebPages.WebPageBase.PopContext() +310
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +375
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +88
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +776
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +81
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__5(IAsyncResult asyncResult) +185
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +26
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +70
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +40
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +70
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +393
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +195
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +128


```

I have also attached screenshots to show the problem
![libmanerror2](https://user-images.githubusercontent.com/8004127/45363645-ef277b80-b5cf-11e8-9916-a80c594aa85a.jpg)
![libmanerror1](https://user-images.githubusercontent.com/8004127/45363646-ef277b80-b5cf-11e8-9385-46c56c05adc4.jpg)

**Comment by justcla** [comment]
Thanks. We'll look into this.

**Comment by dsteinweg** [comment]
I'm seeing this behavior as well.  It's almost as if Visual Studio is explicitly setting ACLs on the files when they're "installed" into the destination location.  I re-apply permission inheritance from the "wwwroot" folder in my ASP.NET Core project to fix them up after installing.

**Comment by JayHayman** [comment]
+1 for same issue with LibMan v1.0 in VS 2019 preview 16.0.0.

Also same thing happens with VS 15.9.4.

Seems any libraries I replace/update/add reset permissions on the files with the destination folder with just SYSTEM, my MSA and Administrator.

**Comment by ponchautf** [comment]
Same issue with VS 2017 & VS 2019.
Any info when this will be solved?

**Comment by jimmylewis** [comment]
This should be fixed with #446

**Comment by richardwerkman** [comment]
@jimmylewis I'm still experiencing this issue with the latests VS2019 16.0.3 release. Has the fix been released already or will it ship soon?

**Comment by jimmylewis** [comment]
@richardwerkman the fix was in 16.0, so you should have it.  

@alexgav can you take another look into this?

**Comment by AdrianHostettler** [comment]
Hy guys, the issue is still happening on VS2017 15.9.12 with Libman 1.0. (Running VS as Admin/elevated). Is this an Issue of VS, or of Library Manager Extension? And is this resolvable by a "relative little" fix, or is it a general conceptual (permissions outside of vs or libman ext.) problem?

Thx for the great tool so far! ;)

**Comment by jimmylewis** [comment]
@AdrianHostettler this is an issue in Library Manager.  The 1.0 implementation used File.Move, which doesn't inherit the ACLs of in the destination file; the fix was to use File.Copy instead, so that the ACLs will be inherited (and the IIS worker will be able to access the file).  (More info on the difference can be found [here](https://support.microsoft.com/en-us/help/310316/how-permissions-are-handled-when-you-copy-and-move-files-and-folders).)

It should be fairly easy to port a fix of this back and build a private version which would work, the changes were in two commits (6075cf13a3ab8d and f0e7f314221e8d).  However, we don't have a good avenue for releasing this change, as it won't make the bar for a VS2017 servicing update (so a 1.0 servicing release isn't an option), and the bump to 2.0 was to accommodate breaking changes in VS2019 (so current 2.0 builds won't work on VS2017).

**Comment by alexgav** [comment]
@richardwerkman - are you still hitting permissions problems in 16.2? Also, to confirm, was your issue on Windows? We recently fixed another permissions issue on Linux.

**Comment by alexgav** [comment]
We fixed this issue in one of the previews for 16.0, so we believe it should be fixed. If anyone is still hitting this exact permission issue in 16.x, please let us know!
